prog:main.o map.o entity.o ennemie.o  background.o  menuuu.o jouer.o pers.o optionn.o utilitaire.o
	gcc main.o map.o entity.o ennemie.o  background.o  menuuu.o jouer.o pers.o optionn.o utilitaire.o -o brog -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
main.o:main.c 
	gcc -c main.c -g

entity.o:entity.c
	gcc -c entity.c -g
ennemie.o:ennemie.c
	gcc -c ennemie.c -g
map.o:map.c
	gcc -c map.c -g
background.o:background.c 
	gcc -c background.c -g

menuuu.o:menuuu.c
	gcc -c menuuu.c -g
jouer.o:jouer.c
	gcc -c jouer.c -g
pers.o:pers.c
	gcc -c pers.c -g
optionn.o:optionn.c
	gcc -c optionn.c -g
utilitaire.o:utilitaire.c
	gcc -c utilitaire.c -g

